### PR TITLE
Create tbct.oscmeta

### PR DESCRIPTION
**Pull request by sctech-tr**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?

- [x] Have you verified that the manifest contains valid JSON?

- [x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?

- [x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

This is a really simple app that you can test your controllers. It's my first Wii project, so it might be bad.

Here is a list of controllers it supports:
- Wiimote
- Nunchuck
- Classic Controller
- GameCube Controller
- Guitar Controller

### CODE REVIEW

**Comment by sctech-tr** [comment]
I'm waiting for a merge, can anybody take a look please?

**Comment by GabubuAvailable** [comment]
> I'm waiting for a merge, can somebody take a look please?

check the reviews i've sent first, fix them, then i'll do it

**Comment by sctech-tr** [comment]
This is probably an unnecessary question but can you explain what you mean by that and what should i do? i'm new to pull requests and sorry if i'm disturbing you

**Review by sctech-tr — COMMENTED** [review]
This pull request adds Text-based Controller Test and wiiRPS to the main Apps repo

**Review by GabubuAvailable — CHANGES_REQUESTED** [review]

**Comment by sctech-tr** [comment]
i think i corrected them. thanks!

**Comment by GabubuAvailable** [comment]
Yeah, both looks good for me now! Thanks!

**Review by GabubuAvailable — APPROVED** [review]

**Comment by Artuto** [comment]
@sctech-tr The same as wcalc, your archive is missing the "wiirps" folder specified in the Manifest, please fix that.

**Comment by sctech-tr** [comment]
I think I messed the folder structure while updating the apps. I'll fix it as fast as I can.

**Comment by sctech-tr** [comment]
I fixed the archive. It now has the folder required.

**Pull request merged**
