### PR TITLE
Add VVVVVV

### PR DESCRIPTION
**Pull request by mardy**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [x] Have you verified that the manifest contains valid JSON?
- [x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

My Wii port of an entertaining 2D platform game: https://thelettervsixtim.es/

### CODE REVIEW

**Comment by Artuto** [comment]
I am checking the original License for this game and I see you are allowed to redistribute everything BUT the assets unless you reach an agreement with the original author.

Have you done this or how are you handling it?

**Comment by ErisonNull** [comment]
mv VVVVVV.elf boot.dol moment

**Comment by mardy** [comment]
> I am checking the original License for this game and I see you are allowed to redistribute everything BUT the assets unless you reach an agreement with the original author.
> 
> Have you done this or how are you handling it?

Hi Artuto, yes, you can find my name at the bottom of this page: https://github.com/TerryCavanagh/VVVVVV/blob/master/License%20exceptions.md

**Comment by mardy** [comment]
> mv VVVVVV.elf boot.dol moment

mmm... no, why? The zip file contains `VVVVVV/boot.dol`, it just needs to be unpacked onto `/apps/`.

**Review by Artuto — APPROVED** [review]

**Pull request merged**
