### PR TITLE
add riivolution for wii mini

### PR DESCRIPTION
**Pull request by playerjmr**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [x] Have you verified that the manifest contains valid JSON?
- [x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

This is a fork of [AerialX/rawksd](https://github.com/AerialX/rawksd) that added support for the wii mini. This probably also works for Wii and vWii but i still want non wii mini owners using the original fork because I think it may have removed some darkcorp checks.

### CODE REVIEW

**Comment by Artuto** [comment]
This ain't gonna work because:

>>> Note: filename.oscmeta is the slug of the application you are submitting. This slug is used to locate files such as "/apps/slug/boot.dol" and "/apps/slug/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

**Comment by playerjmr** [comment]
is it possible to rename the riivolution folder inside of the oscmeta?

**Comment by Artuto** [comment]
> is it possible to rename the riivolution folder inside of the oscmeta?

Nope. Treatments run inside the app's folder (which doesn't exist) so they'll fail.

**Comment by playerjmr** [comment]
> > is it possible to rename the riivolution folder inside of the oscmeta?
> 
> Nope. Treatments run inside the app's folder (which doesn't exist) so they'll fail.

Well, then, I guess the only way to get this to work is if we yeet the original riivolution app and replace it with the wii mini fork (it should work fine on all platforms)

**Comment by Artuto** [comment]
> is it possible to rename the riivolution folder inside of the oscmeta?

Actually it seems we can, yeah.

**Comment by Artuto** [comment]
Is this good for merging?

**Comment by playerjmr** [comment]
> > is it possible to rename the riivolution folder inside of the oscmeta?
> 
> Actually it seems we can, yeah.

Really? So is there a special syntax for this like `contents.rename`? Or is it just done when moving files?

**Comment by Artuto** [comment]
> > > is it possible to rename the riivolution folder inside of the oscmeta?
> > 
> > Actually it seems we can, yeah.
> 
> Really? So is there a special syntax for this like `contents.rename`? Or is it just done when moving files?

Just moving, I think the file is OK right now

**Comment by playerjmr** [comment]
Currently it has the same name as the regular riivolution folder, though if you say it’s fine then it should be good to merge

**Comment by playerjmr** [comment]
Oops didn’t mean to close this

**Review by Artuto — APPROVED** [review]

**Pull request merged**
