### PR TITLE
Update supported platforms

### PR DESCRIPTION
**Pull request by playerjmr**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [x] Have you verified that the manifest contains valid JSON?
- [x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

I updated a ton of apps to have supported platforms. also fixed pair my ds3 and pair my ds4 by adding the `[writes_to_nand]` flag.

### CODE REVIEW

**Comment by Artuto** [comment]
Just a few things:

1. Did you actually test all of them or just a guess
2. You have conflicts due to Mail Patchers

**Comment by playerjmr** [comment]
> 1. Did you actually test all of them or just a guess

I tested the ones that I thought needed to be tested. There was some stuff I already knew and some stuff I’m assuming. I would imagine that all of the homebrew games, emulators, and media would work on all platforms. Stuff like utilities is really what would need to be tested.

> 2. You have conflicts due to Mail Patchers

Oops, I committed that when the wiilink one was still existing.

**Comment by playerjmr** [comment]
i hope i did that right

**Comment by playerjmr** [comment]
nvm i figured it out

**Review by Artuto — APPROVED** [review]

**Pull request merged**
