### PR TITLE
Add ClassiCube Wii Port

### PR DESCRIPTION
**Pull request by emilydaemon**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [x] Have you verified that the manifest contains valid JSON?
- [x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

i don't know why it has the linktag-app commit as well. just squash it and it should be fine...hopefully

### CODE REVIEW

**Comment by dhtdht020** [comment]
had no idea that exists, pretty cool

**Review by GabubuAvailable — APPROVED** [review]
Checked and everything looks good! I forgot that ClassiCube exists...

**Comment by dhtdht020** [comment]
I built Danbo in ClassiCube a long while back
screenshot_2020-12-20-20-56-00

**Comment by GabubuAvailable** [comment]
I like it! lol

**Pull request merged**
