### PR TITLE
Create wcalc.oscmeta

### PR DESCRIPTION
**Pull request by sctech-tr**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [x] Have you verified that the manifest contains valid JSON?
- [x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

wcalc is a basic calculator. you write a number by pressing buttons on the wii remote.
this time i checked if the file contains valid JSON (to the best of my knowledge)

### CODE REVIEW

**Comment by sctech-tr** [comment]
Good evening/morning/afternoon/night!
Can somebody take a look please?

**Review by GabubuAvailable — APPROVED** [review]
Everyhting looks good and the Wii can now do math lol. Now jokes aside, I will approve this app and merge it!

**Comment by Artuto** [comment]
@sctech-tr Your archive is missing the "wcalc" folder specified in the Manifest, please fix that.

**Comment by sctech-tr** [comment]
I fixed the archive. It now has a "wcalc" folder. I think I messed up the folder structure while updating the apps.

**Pull request merged**
