### PR TITLE
Create readmii.oscmeta

### PR DESCRIPTION
**Pull request by sctech-tr**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [x] Have you verified that the manifest contains valid JSON?
- [x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

This is an application that reads txt files. You select one, and it reads it to you. Fairly simple.

### CODE REVIEW

**Comment by emilydaemon** [comment]
> You know Wiixplorer can read txt files too right

I think this app still does have some merit to it, if not for use then at least as a programming example

**Comment by sctech-tr** [comment]
> You know Wiixplorer can read txt files too right

oh right, i forgot about that

**Comment by sctech-tr** [comment]
but it has the deprecated flag, so the users will know this is deprecated, so i think it could be merged.
your choice though.

**Comment by Artuto** [comment]
It ain't deprecated

**Comment by sctech-tr** [comment]
so... will you merge it?

**Comment by GabubuAvailable** [comment]
I don't really see a reason of adding it. Maybe if you plan to add more features on it, then we'll probably change our minds. Great start BTW!

**Comment by sctech-tr** [comment]
looking now, it also seems useless. maybe i will improve it one day, i don't feel like it right now

**Comment by sctech-tr** [comment]
this can stay open

**Pull request closed without merging**
