### PR TITLE
Added 3 Homebrew apps for Wii mini

### PR DESCRIPTION
**Pull request by GabubuAvailable**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [x] Have you verified that the manifest contains valid JSON?
- [x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---
Those apps are specifically made for Wii mini. For more question, you can ask @playerjmr

### CODE REVIEW

**Comment by GabubuAvailable** [comment]
Also don't ask me why ARCME was also added here...

**Comment by dhtdht020** [comment]
are these dangerous if run on a normal wii?

**Comment by GabubuAvailable** [comment]
Like I said, those apps are made specifically for Wii mini. It's also written on version, description and app name.

**Comment by dhtdht020** [comment]
yes but, answer my question.

**Comment by GabubuAvailable** [comment]
> are these dangerous if run on a normal wii?

I think it is but not sure. So I think it's better to wait for @playejmr 's answer because requested me to do so. This PR will not be merged until he will answer, so let's wait for him first.

**Comment by emilydaemon** [comment]
Perhaps Mini specific apps could be added to their own repository, like how themes have their own repository?

**Comment by dhtdht020** [comment]
> Perhaps Mini specific apps could be added to their own repository, like how themes have their own repository?

if the user has to jump through more hoops to have the homebrew browser set up with a secondary repository than to just follow the guide these apps are distributed alongside and manually copy over a few apps then it's probably not worth the hassle.

**Comment by dhtdht020** [comment]
ultimately if things go right and we have a modern client then we can add special flags to mark vwii-specific and mini-specific apps and block them from download on the incorrect system.

we are not there yet, so we must do the calculation if addition of apps justifies the risk factor of displaying it to thousands of potentially unexperienced users

**Comment by dhtdht020** [comment]
I've taken a quick look through Dolphin and these seem to provide enough of a warning as is and do not seem to be particularly problematic, manifests look food to me, will merge.

**Pull request merged**
