### PR TITLE
Add Liichess

### PR DESCRIPTION
**Pull request by RaspberryEqualsPi**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [x] Have you verified that the manifest contains valid JSON?
- [x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

It's a lichess.org client for the Wii using their API. @Artuto @GabubuAvailable @emilydaemon

### CODE REVIEW

**Comment by RaspberryEqualsPi** [comment]
In dolphin or on real hardware? I think it might be an SD card issue

**Comment by GabubuAvailable** [comment]
Dolphin Emulator and yes I have the virtual SD Card prepared already

**Comment by GabubuAvailable** [comment]
Yes

**Comment by RaspberryEqualsPi** [comment]
Can we take this to DMs? I want to see if I can reproduce your problem

**Comment by GabubuAvailable** [comment]
Well I'm busy rn. Let's do tomorrow if you want. 😁👍

**Comment by RaspberryEqualsPi** [comment]
Alright, thanks

**Comment by jazar0** [comment]
lets gooo

**Review by GabubuAvailable — APPROVED** [review]
I tested again and it works. This app can be approved and uploaded.

**Pull request merged**
