### PR TITLE
Add SortMii

### PR DESCRIPTION
**Pull request by bor-real**
it runs some sorting algorithms

### CODE REVIEW

**Comment by GabubuAvailable** [comment]
I suggest you to go with ["github_release"](https://docs.oscwii.org/repository-manager/manifests/source/github-release) as source.

**Comment by GabubuAvailable** [comment]
You also forgot to specify the peripherals. Here's [an example](https://docs.oscwii.org/repository-manager/manifests/example-manifest) on how a manifest should look like.

**Comment by bor-real** [comment]
I`m using `github-release` now, and all it supports is the Wii Remote. Version 0.1.1 of SortMii puts the folder in `sd:/apps/SortMii` now.

**Comment by GabubuAvailable** [comment]
JSON syntax error on manifest :(
(line 12)

**Comment by bor-real** [comment]
> JSON syntax error on manifest :( (line 12)

Forgot a comma

**Comment by bor-real** [comment]
Fixed now

**Comment by GabubuAvailable** [comment]
Everything looks good!

**Pull request merged**
