### PR TITLE
Add Wii Nut

### PR DESCRIPTION
**Pull request by larsenv**
- [X] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [X] Have you verified that the manifest contains valid JSON?
- [X] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [X] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

From Dakotath, the dude which brought you WiiGPTii comes a new game called WiiNut. Despite the name it's SFW, all you do is press a button which says nut on it.

### CODE REVIEW

**Comment by larsenv** [comment]
@Artuto add this

**Comment by Artuto** [comment]
That website is broken

**Comment by larsenv** [comment]
It's only a date error but I will ask him to fix it

**Comment by larsenv** [comment]
@Artuto as of now they cannot seem to fix the SSL thing however you can still visit the website please don't let it stop you from add it

**Comment by Artuto** [comment]
It's not me, it's repoman that cannot access sites with broken SSL.

**Comment by GabubuAvailable** [comment]
Could you also explain what this app do?

**Comment by Artuto** [comment]
I am not disabling SSL verification for a random game.

**Comment by Artuto** [comment]
After internal reviewing and dicussion it has been decided that we'll not be accepting this app.

**Comment by larsenv** [comment]
Is it because of it's innuendos?

**Comment by larsenv** [comment]
@Artuto

**Comment by larsenv** [comment]
Wasn't really expecting it to reach it

**Comment by Artuto** [comment]
No, it's because it provides no value to the repository. It's useless.

**Pull request closed without merging**
