### PR TITLE
Added Wii Chatter

### PR DESCRIPTION
**Pull request by LNLenost**
- [x] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [X] Have you verified that the manifest contains valid JSON?
- [X] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [X] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

<Include a description about the application here, and other information that might be relevant>

Added Wii Chatter

### CODE REVIEW

**Comment by GabubuAvailable** [comment]
What's the reason of changing the filename from `ChristmasCountdown` to `WiiChatter`? Also changing the download link, name, author and version?

**Comment by GabubuAvailable** [comment]
Also I tried it on Dolphin Emulator, and all I get is just an error exception (app crash)

**Comment by LNLenost** [comment]
I used the rep before to add christmascountdown, but @larsenv suggested me
to remove it. So i just renamed ChristmasCountdown.oscmeta to
WiiChatter.oscmeta

**Comment by Artuto** [comment]
Is the crash in Dolphin fixed?

**Comment by LNLenost** [comment]
I mean, I don't have that problem so idk

**Comment by Artuto** [comment]
The app doesn't work and the download has a broken certificate

image

**Comment by LNLenost** [comment]
K, close this then

**Comment by LNLenost** [comment]
Can't. the app isn't mine I just found it and I discovered it was used some
years ago, so I tried to add it here

**Pull request closed without merging**
